# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
_extends: .github:.github/settings.yml

# repo-specific settings

repository:
  name: "portefaix-krm"
  description: "Portefaix KRM"

labels:
- name: "cloud/gcp"
  description: "Cloud Provider / Google Cloud Provider"
  color: "068082"

- name: "cloud/aws"
  description: "Cloud Provider / Amazon AWS"
  color: "068082"

- name: "cloud/azure"
  description: "Cloud Provider / Microsoft Azure"
  color: "068082"

- name: "cloud/scaleway"
  description: "Cloud Provider / Scaleway"
  color: "068082"

- name: "cloud/digitalocean"
  description: "Cloud Provider / Digital Ocean"
  color: "068082"

- name: "cloud/alicloud"
  description: "Cloud Provider / Alicloud"
  color: "068082"

- name: "cloud/exoscale"
  description: "Cloud Provider / Exoscale"
  color: "068082"

- name: "cloud/homelab"
  description: "Cloud Provider / Homelab"
  color: "068082"

- name: "cloud/cicd"
  description: "Cloud Provider / CICD"
  color: "068082"

- name: "cloud/vultr"
  description: "Cloud Provider / Vultr"
  color: "068082"

- name: "cloud/civo"
  description: "Cloud Provider / Civo"
  color: "068082"

- name: "krm/crossplane"
  description: "Crossplane"
  color: "cc317c"

- name: "krm/gcp-config-connector"
  description: "GCP Config Connector"
  color: "cc317c"

- name: "krm/aws-controllers-k8s"
  description: "AWS Controllers for Kubernetes"
  color: "cc317c"

- name: "krm/azure-service-operator"
  description: "Azure Service Operator"
  color: "cc317c"

- name: "needs/cloud"
  description: "Indicates a PR lacks a `cloud/foo` label and requires one."
  color: "D669BE"

- name: "area/kubernetes"
  description: "Kubernetes"
  color: "cc317c"

- name: "area/terraform"
  description: "Terraform"
  color: "cc317c"

- name: "area/inspec"
  description: "Inspec"
  color: "cc317c"

- name: "area/ansible"
  description: "Ansible"
  color: "cc317c"

- name: "area/github"
  description: "Github"
  color: "cc317c"

- name: "dependency/terraform"
  description: "Dependency Terraform"
  color: "6fcb70"

- name: "dependency/docker"
  description: "Dependency Docker"
  color: "6fcb70"

- name: "dependency/github"
  description: "Dependency Github Actions"
  color: "6fcb70"

- name: "dependency/krm"
  description: "Dependency KRM"
  color: "6fcb70"
