# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: azure.crossplane.io/v1alpha3
kind: ResourceGroup
metadata:
  name: portefaix-krm-azure-aks
spec:
  location: West Europe
  providerConfigRef:
    name: crossplane-azure
---
apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: portefaix-krm-azure
spec:
  resourceGroupNameRef:
    name: portefaix-krm-azure-aks
  vnetSubnetIDRef:
    name: portefaix-krm-azure
  location: West Europe
  version: 1.18.10
  nodeCount: 1
  nodeVMSize: Standard_B2s
  # dnsNamePrefix: portefaix-krm-azure-aks
  disableRBAC: false
  providerConfigRef:
    name: portefaix-azure
  writeConnectionSecretToRef:
    name: portefaix-krm-azure-aks
    namespace: crossplane-system