# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  app.kubernetes.io/name: portefaix-krm-azure
  app.kubernetes.io/instance: portefaix-krm-azure-app
  app.kubernetes.io/component: krm-crossplane
  app.kubernetes.io/version: v0.1.0
  app.kubernetes.io/part-of: portefaix-krm-azure
  app.kubernetes.io/managed-by: kustomize
  portefaix.xyz/version: v0.19.0
  crossplane.io/version: v0.14.0
  crossplane.io/provider: azure-v0.17.0
fieldSpecs:
- path: metadata/labels
  create: true
