# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


---
apiVersion: sks.exoscale.jet.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: portefaix-krm
spec:
  forProvider:
    description: "Managed with Crossplane Exoscale Provider"
    zone: de-fra-1
    name: portefaix-krm
  providerConfigRef:
    name: crossplane-exoscale
---
apiVersion: sks.exoscale.jet.crossplane.io/v1alpha1
kind: Nodepool
metadata:
  name: portefaix-krm-core
spec:
  forProvider:
    clusterIdRef:
      name: portefaix-krm
    securityGroupIdRefs:
    - name: portefaix-krm-sks
    zone: de-fra-1
    name: portefaix-krm-core
    instanceType: "standard.medium"
    size: 1
  providerConfigRef:
    name: crossplane-exoscale
---
apiVersion: sks.exoscale.jet.crossplane.io/v1alpha1
kind: Nodepool
metadata:
  name: portefaix-krm-ops
spec:
  forProvider:
    clusterIdRef:
      name: portefaix-krm
    securityGroupIdRefs:
    - name: portefaix-krm-sks
    zone: de-fra-1
    name: portefaix-krm-ops
    instanceType: "standard.medium"
    size: 1
  providerConfigRef:
    name: crossplane-exoscale
