# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: portefaix-krm-gcp
spec:
  properties:
  forProvider:
    displayName: "portefaix-krm-crossplane"
    description: "Portefaix KRM Crossplane"
  deletionPolicy: Delete
  providerConfigRef:
    name: portefaix-gcp
---
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccountKey
metadata:
  name: portefaix-krm-gcp
spec:
  properties:
  forProvider:
    # Google Cloud API RRN of a ServiceAccount is expected in "serviceAccount" field
    # serviceAccount: projects/crossplane-playground/serviceAccounts/perfect-test-sa@crossplane-playground.iam.gserviceaccount.com
    serviceAccountRef:
      name: portefaix-krm-gcp
    # keyAlgorithm: "KEY_ALG_RSA_2048"
    # privateKeyType: "TYPE_GOOGLE_CREDENTIALS_FILE"
    # publicKeyType: TYPE_RAW_PUBLIC_KEY
  deletionPolicy: Delete
  providerConfigRef:
    name: portefaix-gcp
  writeConnectionSecretToRef:
    name: portefaix-krm-gcp-sa-key
    namespace: crossplane-system
---
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccountPolicy
metadata:
  name: portefaix-krm-gcp
spec:
  forProvider:
    serviceAccountRef:
      name: portefaix-krm-gcp
    policy:
      bindings:
        - role: roles/iam.workloadIdentityUser
          members:
            - serviceAccount:portefaix-krm.svc.id.goog[vault-system/vault]
  providerConfigRef:
    name: portefaix-gcp
