# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  app.kubernetes.io/name: portefaix-cluster-api-aws-eks
  app.kubernetes.io/instance: portefaix-cluster-api-aws-eks-app
  app.kubernetes.io/component: krm-cluster-api
  app.kubernetes.io/version: v0.1.0
  app.kubernetes.io/part-of: portefaix-cluster-api-aws-eks
  app.kubernetes.io/managed-by: kustomize
  clusterapi.k8s.io/version: v1.2.4
  clusterapi.k8s.io/provider: v1.5.1
fieldSpecs:
- path: metadata/labels
  create: true
